### ISSUE TITLE
Basic Docs

### ISSUE THREAD

**Issue by rlaurente** [light-tech/MiniGit#2]
Hi there

Can you please provide sample codes and basic usage docs ?

Thanks

**Comment by light-tech** [comment]
It should be as easy as

```swift
let credentialsManager = CredentialsManager(urlToLocalFileToStoreCredentials) // Or extends CredentialsManager however you see fit

let repo = GitRepository(urlToLocalRepo, credentialsManager)

repo.open()
if repo.exists() {
}
// Or
repo.clone("https://github.com/light-tech/MiniGit.git")
```

**Comment by rlaurente** [comment]
Thanks, btw do you have example content of credentials manager file ?

**Comment by light-tech** [comment]
The CredentialsManager was mostly meant to be used as data model for user interface where users can manage their credentials. If you want to craft some test credentials, you can add it in the code:

```swift
let cred = Credential(
    id: "An example credential",
    kind: .password,
    targetURL: "https://github.com/light-tech/", // This allows the library to automatically supply this credential to all remote repository whose URL starts with https://github.com/light-tech/
    userName: "light-tech",
    password: "Personal Access Token Created from Github Website")

// This will save the credential to the supplied URL
credentialsManager.addOrUpdate(nil, cred)
```

**Comment by rlaurente** [comment]
Hi there, just got back from holidays.

I will test on this thanks!

**Comment by rlaurente** [comment]
Hi @light-tech 

Very cool, It works! btw do you have example on adding the progress in clone ? 

Thanks

**Comment by light-tech** [comment]
The class [`MiniGit.GitRepository`](https://github.com/light-tech/MiniGit/blob/main/Sources/MiniGit/GitRepository.swift)'s convenient method `clone` reports progresses via its `remoteProgress` member which conforms to `ObservableObject` so you could bind its data if you are using SwiftUI.
```swift
struct MyCloneProgressView {
    @ObservedObject var progress: RemoteProgress

    var body: some View { /* your view implementation to display progress information in RemoteProgress */ }
}
```

If you want to handle the progress yourself (printing to the console for example), you could use the more general version of `clone` method supplied in the superclass [`XGit.Repository`](https://github.com/light-tech/MiniGit/blob/main/Sources/XGit/include/Repository.h):

```swift
class MyCustomRemoteProgressHandler: RemoteProgressProtocol {
     // See https://github.com/light-tech/MiniGit/blob/main/Sources/XGit/include/RemoteProgressProtocol.h
     // and https://github.com/light-tech/MiniGit/blob/main/Sources/MiniGit/RemoteProgress.swift for an example
}

// Then to clone:
repo.clone(remoteRepoUrl, MyCustomRemoteProgressHandler(), nil, nil)
```

**Comment by rlaurente** [comment]
That works, thanks!

btw, how to implement git pull origin main ?
I also tried fetch but I got exc_bad_access error on runtime

Thanks

**Comment by light-tech** [comment]
Well, pull = fetch + merge + commit (sometimes)

Unfortunately, the current UI-focused design doesn't expose much of the "scriptable features" of libgit2. You might want to add some methods in XGit to retrieve a `Remote` by name (e.g. "origin") and a branch (a.k.a. `Reference`) by name (e.g. "main") as `.fetch` requires a `Remote` whereas `merge` needs a `.Reference` as input. But it is still do-able at the moment: You can iterate through all the references in `repo.commitGraph.refs` and `repo.getRemotes()`.

**Comment by light-tech** [comment]
We are adding sample app at https://github.com/light-tech/MiniGit-SampleApp so will close this issue.
