### ISSUE TITLE
How to use `git status` to track new files  and `git diff`?

### ISSUE THREAD

**Issue by Heyya-x** [light-tech/MiniGit#8]
In the documentation, I saw that the package includes the functionality of `git diff` and `git status`. I checked the examples in [MiniGit-SampleApp](https://github.com/light-tech/MiniGit-SampleApp),  but it did not provide information on how to use `git diff` and `git status`.

I examined the source code, but couldn't figure out how to view tracked and untracked files. I accessed the `path` attribute of `theNewFile` and `theOldFile` in `repo.status.stagedChanges.deltas`, but the value is always `nil`.

Meanwhile, how can I use 'git diff' to view the modification information of staged files?

Could you please add usage examples for these two functionalities in the [MiniGit-SampleApp](https://github.com/light-tech/MiniGit-SampleApp)?

**Comment by Heyya-x** [comment]
My bad, I solved this problem.

**Comment by liunina** [comment]
> My bad, I solved this problem.

so? how did you solved it?

**Comment by Heyya-x** [comment]
> > My bad, I solved this problem.
> 
> so? how did you solved it?

I just forgot to update the view after creating or modifying a file in the current folder.
